CREATE TABLE dbo.Users (
    UserId BIGINT NOT NULL PRIMARY KEY IDENTITY
    , FullName NVARCHAR(250) NULL
    , RoleId BIGINT NOT NULL
    , Email VARCHAR(250) NOT NULL UNIQUE
    , Password VARCHAR(250) NOT NULL
    , IsActive BIT NOT NULL DEFAULT 1
    , CreatedBy BIGINT NULL
    , UpdatedBy BIGINT NULL
    , CreatedAt DATETIME2 NULL
    , UpdatedAt DATETIME2 NULL CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(RoleId)
    )
